### ISSUE TITLE
Unable to import rapture-cli inside intellij

### ISSUE THREAD

**Issue by lucianenache** [propensive/rapture-cli#11]
Hello,

I have an intellij 14.1.1 scala project.

My sbt file is the following 

```scala

organization := "me.lessis"

name := "default"

version := "0.1.0-SNAPSHOT"

libraryDependencies ++= Seq("com.propensive" %% "rapture-core" % "1.1.0")

libraryDependencies ++= Seq("com.propensive" %% "rapture-cli" % "0.9.0")
```

Inside the project I am using Java 7 and Scala 2.10.4 versions.

When I try to resolve the two rapture dependencies, I get an error stating the following 

```scala
Error:Error while importing SBT project:
...
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: unresolved dependency: com.propensive#rapture-cli_2.10;0.9.0: not found
[error] Use 'last' for the full log.

See complete log in C:\Users\lucio\.IntelliJIdea14\system\log\sbt.last.log
```

Can anyone tell me what am I doing wrong ?

**Comment by propensive** [comment]
Sorry for taking so long to reply, but thanks for your interest in the project, though I fear than the README for the project may have been misleading. Rapture CLI isn't available yet as a binary, as it's still got some critical bugs which I don't want to release, and it's have very limited testing.

On a more positive note, I am using it in my own projects, and many features (like tab completion) work very well, and are very flexible, but it's not ready yet. Hopefully I shall be able to make a release in a couple of months.

I've updated the README file to remove the lies about it being available. (That was copy/paste laziness, I'm afraid.)

**Comment by lucianenache** [comment]
Thanks, if you do need help with the project I would gladly contribute.

**Comment by propensive** [comment]
Thanks, Lucian - I appreciate it. Maybe once I'm confident enough about how it's working to announce it publicly, you could get involved. I'm reluctant to have anyone else invest time in it until it's clearly I'm not going to massively change the design, but once I have made that decision, I'll be keen to get contributors!

**Comment by lucianenache** [comment]
Great, then I'll be keeping an eye on it.
